---
abstract: 'Internationalized Resource Identifiers'
author:
  - 'Gregory Todd Williams  C<< <gwilliams@cpan.org> >>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  URI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IRI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 2
  perl: 5.14.0
resources:
  bugtracker: https://github.com/kasei/perl-iri/issues
  homepage: http://search.cpan.org/dist/IRI/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kasei/perl-iri/
version: 0.001_01
